### ISSUE TITLE
What is the current state of the stable Pantheon desktop on Fedora?

### ISSUE THREAD

**Issue by 9Morello** [decathorpe/elementary-stable-rpms#10]
Hello!
I've read your posts on /r/elementary, but didn't see any news recently. How is it going?

Good work. Really nice to see someone bringing Pantheon to another distro.

**Comment by decathorpe** [comment]
I post more regularly on my own website, <https://decathorpe.com/> - I don't post everything on reddit.

The session should work well enough on f24 and f25, although there are some minor bugs left (as you can see from the other reported issues).

**Comment by taohansen** [comment]
On Fedora 25 I see no cursor, no wingpanel with only a primitive dock on the left hand side after first enabling your repo and then installing pantheon-desktop.

**Comment by decathorpe** [comment]
@taohansen That sounds like there are multiple problems. Can you confirm whether the cerbere, wingpanel, gala, slingshot-launcher and plank packages are installed?
