### ISSUE TITLE
Sound switchboard plug

### ISSUE THREAD

**Issue by ziflex** [decathorpe/elementary-stable-rpms#12]
Hi there,

first of all, thank you for the you you have been doing - I really enjoy Pantheon, despite missing parts.

So, regarding  missing parts. Today, I noticed that there is no way to configure sound via settings panel. The only way to do so (just turn on/off and adjust volume) via top bar.

**Comment by decathorpe** [comment]
I am aware of this limitation. The sound plug for switchboard is (as far as I know) the last plug elementary started working on. There is a git repository where you can see the current state of development (https://github.com/elementary/switchboard-plug-sound), but there hasn't been a stable release yet that I can target for packaging for fedora.

I'll add a sound plug package to my nightly builds repository soon, but I'm not sure if that's what you want or need.

**Comment by ziflex** [comment]
@decathorpe I understand that. This status update is fine, thanks! Will wait :)

**Comment by decathorpe** [comment]
Nightly builds of the sound plug master branch are now available via my elementary-nightly COPR repository. As soon as a stable release is tagged, I'll add it to the elementary-stable COPR (or even the official fedora repositories).
