### ISSUE TITLE
switchboard-plug-networking doesn't work on Fedora 27

### ISSUE THREAD

**Issue by juanfgs** [decathorpe/elementary-stable-rpms#15]
Both on this one and on nightly switchboard-plug-networking fail to start, apparently because it makes uses of libnma and libnm-util which is not allowed by the latest version of the library. Additionally this causes wingpanel to raise a fatal exception. 

The problem can be solved by uninstalling switchboard-plug-networking, which makes it impossible to use wingpanel's network applet and it's extremely unconvenient for laptops.

**Comment by decathorpe** [comment]
I just checked on my own machine, and the stable switchboard-plug-networking from the fedora repos works fine here ... I also ran switchboard from the command line and it doesn't produce any error or warning messages. Can you run `switchboard` on the command line, navigate to the Network plug, close the application, and paste the console output here?

**Comment by juanfgs** [comment]
Hello, 

Well it actually seems to affect wingpanel rather than switchboard. If I start a new session after installing switchboard-plug-networking wingpanel keeps crashing and running again. So I killed cerbere, and ran wingpanel manually. I got [this error](https://gist.github.com/juanfgs/43085ef9d0ec42427770db664c45d9be)

The actual  error is: [libnm-util] libnm symbols detected; Mixing libnm with libnm-util/libnm-glib is not supported
Trace/breakpoint trap (`core' generado)

**Comment by decathorpe** [comment]
Did you install the network indicator from the nightly repo? I guess that would cause this error - mixing and matching stable and nightly packages isn't a good idea.

**Comment by juanfgs** [comment]
Hi, you were right! I tested the nightly but then rolled back to stable, for some reason dnf keep downloading the nightly version of the indicator. I'm cleaning everything up and reinstalling the appropiate packages :)

**Comment by decathorpe** [comment]
So ... is it working again now?

**Comment by juanfgs** [comment]
yes, it is working. Thanks.

**Comment by decathorpe** [comment]
Good 🙂
