### ISSUE TITLE
Wingpanel in fedora 27 crashes

### ISSUE THREAD

**Issue by mthomos** [decathorpe/elementary-stable-rpms#16]
My system has only RPM Fusion repos added.

[INFO 12:43:13.773889] Application.vala:154: System Panel version: 2.0.4
[INFO 12:43:13.773930] Application.vala:156: Kernel version: 4.14.8-300.fc27.x86_64
[FATAL 12:43:14.003428] [GLib-GIO] g_dbus_connection_call_sync_internal: assertion 'object_path != NULL && g_variant_is_object_path (object_path)' failed
[FATAL 12:43:14.025287] display_widget_set_icon_name: assertion 'self != NULL' failed
[FATAL 12:43:14.025569] display_widget_set_icon_name: assertion 'self != NULL' failed
[WARNING 12:43:14.064167] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.064214] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.108041] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.108090] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.108423] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.108452] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.108659] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.108685] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.109050] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.109076] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.109456] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.109484] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.109812] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.109838] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.110033] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.110060] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.110326] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.110353] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.110670] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.110696] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.110969] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.110996] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.111178] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.111205] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.111524] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.111550] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.111867] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.111893] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.112168] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.112195] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.112474] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.112501] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.112564] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.112589] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.112813] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.113057] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.113083] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.113389] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.113416] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.113626] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.113651] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.113834] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.114082] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.114107] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.114401] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.114427] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.114481] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.114506] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.114772] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.114797] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.115064] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.115090] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.115303] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.115329] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.115568] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.115617] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.115642] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.115899] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.115925] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.116114] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.116139] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.116189] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.116213] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.116455] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.116481] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.116699] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.116725] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.116993] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.117018] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.117217] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.117254] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.117575] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.117601] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.117846] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.117872] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.118121] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.118147] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.118446] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.118472] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.118753] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.118779] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.119038] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.119064] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.119313] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.119340] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.119576] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.119601] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.119838] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.119864] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.120122] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.120148] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.120433] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.120459] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.120678] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.120704] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.120975] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.121000] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.121211] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.121248] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.121504] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 12:43:14.121681] [Gtk] (gtkicontheme.c:5494):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[10:43:14.413993 Gtk-Critical] gtk_widget_set_no_show_all: assertion 'GTK_IS_WIDGET (widget)' failed
[10:43:14.414011 Gtk-Critical] gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed
[10:43:14.418765 Critical] string_to_string: assertion 'self != NULL' failed
[10:43:14.424536 Critical] string_to_string: assertion 'self != NULL' failed
[10:43:14.548793 Warning] [DesktopFileInfo] Unable to get exec for Other
[10:43:14.559047 Warning] [DesktopFileInfo] Unable to get exec for GNOME Shell integration
[10:43:14.598760 Warning] [DesktopFileInfo] Unable to create AppInfo
[10:43:14.699775 Critical] PlugsManager.vala:58: get_plug () not found in /usr/lib64/switchboard/hardware/pantheon-power/logind-helper
[ERROR 12:43:14.761081] [libnm] libnm-util symbols detected; Mixing libnm with libnm-util/libnm-glib is not supported
Trace/breakpoint trap (core dumped)

**Comment by decathorpe** [comment]
Did you install packages from the elementary-nightly COPR repository? It currently causes this issue.

**Comment by mthomos** [comment]
Nope stable

**Comment by juanfgs** [comment]
Hi,
are you sure you didn't enable nightly at some point then rolled back?

what's the output of dnf info wingpanel-indicator-networking ?

**Comment by mthomos** [comment]
Oh i found it, it was firewalld. I made a modifcation for me that broke wingpanel-indicator-networking. Thanks for your help!
