### ISSUE TITLE
Pantheon Files file-roller integration?

### ISSUE THREAD

**Issue by juanfgs** [decathorpe/elementary-stable-rpms#17]
Hi, 

I like Pantheon Files but sadly cannot use it daily because it lacks basic integration with file-roller (extract to.., compress). Is this something that is wrong with my setup or is something not yet implemented/ported?

Thanks.

**Comment by decathorpe** [comment]
It looks like elementary is shipping a patched version of file-roller with elementaryOS which includes two contracts for compressing and uncompressing files. Since I can't patch file-roller to do this on fedora, I'll think about shipping the contracts with pantheon-files itself.

**Comment by decathorpe** [comment]
I've been shipping these "compress" and "extract here" contracts with `pantheon-files` itself for some time now, so this should be fixed.
