### ISSUE TITLE
extended window shadows and drag areas in non-Elementary apps

### ISSUE THREAD

**Issue by elektronen** [decathorpe/elementary-stable-rpms#19]
I've noted this issue using both the elementary-stable and elementary-nightly builds. The laptop I use as a daily driver for work was installed from the base Fedora 27 Live DVD, then augmented with MATE, and most recently Cinnamon (which I then removed). In Elementary apps, window shadows and drag areas are as expected, with the baseline being a standard Elementary OS Loki 0.4.1 install on another laptop.

All non-Elementary apps, e.g. Thunderbird, Firefox, MATE's Geany editor, etc. have what seem like doubled or amplified window shadows and drag areas. While Elementary apps might start at 20 pixels from the window edge, on non-Elementary apps this is uniformly 4x-5x that width, as though there are two compositors at work on these.

I have not been able to track down any gsettings that would account for this, but have confirmed that this issue does not exist on the Elementary OS Loki 0.4.1 laptop, where all non-Elementary apps exhibit uniform window and drag area behavior.

**Comment by elektronen** [comment]
It occurs to me there's one other possibility, and that's 'elementary-theme' may not be compatible with GTK3 3.22, since Loki 0.4.1 is presently only at GTK3 3.18.

**Comment by decathorpe** [comment]
This sounds like either a bug in gala's HiDPI support (less likely) or theme incompatibility you mentioned (more likely). Does using a different theme fix the problem?

**Comment by elektronen** [comment]
I tested manually installed OSX-Arc_White 1.4.7 and the Fedora-supplied Arc theme, and both exhibit uniform window behavior between Elementary apps and non-Elementary ones. Unfortunately, I like the default theme, but it seems I'll be waiting until Juno is farther along before these issues get fixed. :/

**Comment by decathorpe** [comment]
Ok, I’m glad it's a simple issue after all, but as you said, there's nothing we can do but wait for upstream to finally properly support Gtk-3.22.
