### ISSUE TITLE
Wingpanel is always shown on top of fullscreened windows like Totem or Audience

### ISSUE THREAD

**Issue by nekohayo** [decathorpe/elementary-stable-rpms#3]
There is currently no way to have a real movie experience with pantheon-session in F25 as the top panel always remains overlaid on top of the video, even when video players are fullscreened... I doubt that would be a "by design" feature of Elementary?

**Comment by nekohayo** [comment]
For what it's worth, this also affects Plank, if the dock is configured to not auto-hide when a window overlaps it.

**Comment by decathorpe** [comment]
I can only reproduce this on fedora 25 (and not on fedora 24 or elementaryOS 0.4 itself), so as far as I can tell, the only moving part that could result in this change is `libmutter` with version 3.22. I will ask the upstream developer for help with troubleshooting.

**Comment by decathorpe** [comment]
It looks like this has been fixed - at least I can't reproduce the issue on fedora 27 anymore.
