### ISSUE TITLE
Battery indicator is always shown, even on a desktop computer

### ISSUE THREAD

**Issue by nekohayo** [decathorpe/elementary-stable-rpms#5]
Strangely enough, I have a battery indicator on my wingpanel on the top-right corner of the screen, but this is a desktop computer with no battery...

**Comment by lewisgoddard** [comment]
What shows in the indicator? This also detects wireless devices such as headphones and keyboards/mice that use batteries.

**Comment by nekohayo** [comment]
...ooooh. Just realized now that it shows "Keyboard..." and calulates into the infinite because I have a logitech K400 keyboard dongle, and the keyboard is turned off... so it can't ever calculate that until I switch it on.

**Comment by lewisgoddard** [comment]
In that case, this can probably be closed. This is intentional behavior in elementary.

**Comment by decathorpe** [comment]
Thanks @lewisgoddard for helping me troubleshoot! I suspect the issue can be treated as "resolved".
