### ISSUE TITLE
Elementary's Slingshot launcher + Plank dock banish the GNOME Control Center

### ISSUE THREAD

**Issue by nekohayo** [decathorpe/elementary-stable-rpms#6]
So this one might be a touchy subject, but... the only way to access gnome-control-center is to type that command in full, until the end, in Slingshot's search bar. It is never offered as an autocompletion choice.

Whatsmore, when you launch it, you cannot pin it to the dock.

I personally consider g-c-c to be superior in various aspects compared to Elementary's control center, so I would prefer to have easy access to it instead of force-hiding it away as if it didn't exist.

**Comment by brunelli** [comment]
The `gnome-control-center.desktop` file has `OnlyShowIn=GNOME;Unity;`. Commenting this line will probably make it appear.

**Comment by nekohayo** [comment]
I tested, and your hypothesis is correct! Then would it be acceptable to elementary folks for me to propose a patch in upstream GNOME to fix this?

**Comment by brunelli** [comment]
I don't know, but there's a reason for this line to be like this. Switchboard suits elementary OS better, as it is developed by the same team and with Pantheon's features in mind. GNOME Control Center is used by default only in GNOME and Unity, so I don't see a reason for this to be changed in upstream, but maybe you can present good arguments to them.

I suggest you make a copy of the desktop file to `~/.local/share/applications/` and edit that line in the new file, so the changes will persist after the package is updated/reinstalled.

**Comment by nekohayo** [comment]
I acknowledge the need for the existence of Elementary's "switchboard", just that users shouldn't always be prevented from seeing alternate control panels (from a very close desktop environment) if they actively seek them out...

* g-c-c has more features, like color management, wacom tablets configuration, sound, bluetooth, etc. so I still find it useful
* g-c-c does not come preinstalled in elementary (AFAIK), and here I installed gnome-control-center myself, so I would have liked to be able to access it mostly like any other app
* letting g-c-c be shown as a search result does not diminish Switchboard, since Switchboard is still accessible as a prime target in Wingpanel's top-right menus
* Gala does not offer "alt+F2" run functionality like gnome-shell to launch arbitrary commands with autocompletion (Daniel decided some years ago that "this feature does not belong here, because we have Slingshot to launch apps")... an approach that shows its limitations here, since slingshot does not offer g-c-c as a launchable until you type every single letter, down to the last one...

**Comment by decathorpe** [comment]
Huh, it seems you already worked out why it doesn't show up in a Pantheon session.

Also, I understand why you would (sometimes at least) prefer to use g-c-c during a Pantheon session (for the reasons you mentioned).

As a side note, on elementaryOS, switchboard includes a few settings panels from unity-control-center (which is a gnome-control-center fork), for example a bluetooth settings panel (which is missing from switchboard yet).

Still, I think this is not an "issue" that I can (or should) attempt to fix ... so, the question is:
Is having a modified copy of `gnome-control-center.desktop` in your `~/.local/share/applications/` folder enough of a resolution of the issue for you?
