### ISSUE TITLE
Colorful "do-not-disturb" icon is always shown in wingpanel's top-right corner, regardless of the notification state

### ISSUE THREAD

**Issue by nekohayo** [decathorpe/elementary-stable-rpms#8]
This colored icon never changes, and sticks out like a sore thumb among the other symbolic icons:

![elementary-dnd](https://cloud.githubusercontent.com/assets/479401/20637768/4111bea8-b35f-11e6-9594-f5663acf5958.png)

**Comment by decathorpe** [comment]
You are seeing the icon that is displayed if a requested icon is not provided by the icon theme in use. Which icon theme are you using?

**Comment by nekohayo** [comment]
I was about to say "It happens with the 'Elementary' icon theme just like the 'Adwaita' icon theme" but when testing today the Elementary icon theme is not affected (maybe there was an update recently?) so I guess it's not actually a bug here.

**Comment by decathorpe** [comment]
Not all icon themes provide the symbolic icons necessary for the indicator to look right. I'm just glad that it's not a bug :)
